title: 黄明志个人主页【非官方】
description: 黄明志个人主页【非官方】
github:
  is_project_page: false
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

socials: 
  website: https://namewee4896.com/
  youtube: https://www.youtube.com/c/namewee
  facebook: https://www.facebook.com/namewee/
  
